# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Piotr Szewczul"
resume_title:                   "Data Engineer \t|\t ETL Engineer \t|\t Python Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "piotrek.szewczul19@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "511 111 369"
resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "piotrek.szewczul19@gmail.com \t|\t +48 511 111 369"
display_header_contact_info:    "true"

resume_header_intro: "<p>Data & IT Specialist. Three years of hands-on experience in the Data industry, with a focus on efficiency and technical excellence. I excel at learning on the fly and staying composed under pressure. I am a proactive individual who is deeply committed to lifelong learning, always seeking new challenges to further refine my expertise and become a better Engineer every day.</p>"
resume_header_intro_pl: "<p>Specjalista Data & IT. Ponad Trzy lata praktycznego doświadczenia w branży Data, z silnym nastawieniem na wydajność i doskonalenie techniczne. Skutecznie uczę się w biegu i zachowuję spokój pod presją czasu. Jestem osobą proaktywną, oddaną idei ciągłego kształcenia , która zawsze szuka nowych wyzwań, aby doskonalić swoją wiedzę i każdego dnia stawać się lepszym inżynierem.</p>"

resume_looking_for_work:        "yes"

resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
#resume_section_recognition:     true
resume_section_links:           true
# resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/piotrek991"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/piotr-szewczul-70891720b/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
